# Generated by Django 5.2.13 on 2026-04-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='empresa_logos/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Administrador Global'), ('JEFE', 'Jefe de Mantenimiento'), ('TECNICO', 'Técnico de Mantenimiento'), ('ESTUDIANTE', 'Operador')], default='ESTUDIANTE', max_length=20),
        ),
    ]
